type: object
description: A metadataset providing details on the provider of this OOAPI implementation 
required:
  - contactEmail
  - specification
  - documentation
properties:
  contactEmail:
    type: string
    description: Contact e-mail address of the service owner
    format: email
    maxLength: 256
    example: admin@universiteitvanharderwijk.nl
  specification:
    type: string
    description: URL of the API specification (YAML or JSON, compliant with [Open API Specification v3](https://github.com/OAI/OpenAPI-Specification/))
    format: uri
    maxLength: 2048
    example: https://rawgit.com/open-education-api/specification/v3/docs.html#tag/course-offerings/paths/~1course-offerings/get
  documentation:
    type: string
    description: URL of the API documentation, including general terms and privacy statement
    format: uri
    maxLength: 2048
    example: https://open-education-api.github.io/specification/v4/docs.html
  ext:
    $ref: './Ext.yaml'
