name: Lint v6 specification

on:
  pull_request:
    branches:
      - 6.0  # Replace with your specific branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Lint OpenAPI Specification
        run: redoc-cli lint v6/spec.yaml