name: Lint v6 specification

on:
  pull_request:
    branches:
      - 6.0  # Replace with your specific branch name
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Redoc CLI
        run: npm install -g @redocly/cli@1.34.2

      - name: Lint OpenAPI Specification
        run: npx @redocly/cli lint v6/spec.yaml --skip-rule security-defined

